// GENERATED BY script — split from psicoterapiaApproaches.ts (10 families).
import type { PsychologyApproach } from '../../types';
import { FAM_01_APPROACHES } from './fam-01-psicanalitica-psicodinamica';
import { FAM_02_APPROACHES } from './fam-02-existencial-humanista';
import { FAM_03_APPROACHES } from './fam-03-comportamental';
import { FAM_04_APPROACHES } from './fam-04-cognitivo-comportamental';
import { FAM_05_APPROACHES } from './fam-05-sistemica-familiar-casais';
import { FAM_06_APPROACHES } from './fam-06-construtivista-narrativa';
import { FAM_07_APPROACHES } from './fam-07-interpessoal-relacional';
import { FAM_08_APPROACHES } from './fam-08-integrativa-eclerica';
import { FAM_09_APPROACHES } from './fam-09-social-cultural-genero';
import { FAM_10_APPROACHES } from './fam-10-pragmaticos-objetivo';

/** Todas as 97 abordagens de psicoterapia, concatenadas por família. */
export const PSICOTERAPIA_APPROACHES: PsychologyApproach[] = [
  ...FAM_01_APPROACHES,
  ...FAM_02_APPROACHES,
  ...FAM_03_APPROACHES,
  ...FAM_04_APPROACHES,
  ...FAM_05_APPROACHES,
  ...FAM_06_APPROACHES,
  ...FAM_07_APPROACHES,
  ...FAM_08_APPROACHES,
  ...FAM_09_APPROACHES,
  ...FAM_10_APPROACHES,
];

export type { PsychologyApproach };
