// GENERATED BY content/build-temple-facades.mjs — NÃO EDITAR MANUALMENTE.
import type { TempleAuthor } from '../../types';
import authorsJson from './authors.json' with { type: 'json' };

export interface CuratedAuthorsFile {
  schemaVersion: number;
  generatedAt: string;
  stats: Record<string, number>;
  families: string[];
  authors: TempleAuthor[];
}

export const curatedAuthorsFile = authorsJson as unknown as CuratedAuthorsFile;
