// GENERATED BY content/build-temple-facades.mjs — NÃO EDITAR MANUALMENTE.
import type { TempleComparison } from '../../types';
import comparisonsJson from './comparisons.json' with { type: 'json' };

export interface ComparisonsFile {
  schemaVersion: number;
  generatedAt: string;
  scope: string;
  counts: Record<string, number>;
  canonicalAxes: string[];
  schemaNotes: string[];
  fontes: Array<Record<string, unknown>>;
  comparacoes: TempleComparison[];
}

export const comparisonsFile = comparisonsJson as unknown as ComparisonsFile;
