// GENERATED BY content/build-temple-facades.mjs — NÃO EDITAR MANUALMENTE.
import conceptIndexJson from './concept-index.json' with { type: 'json' };

export interface ConceptIndexEntry {
  id: string;
  name: string;
  domainId: string;
  domainName: string | null;
  definition: string;
}

export const conceptIndex = conceptIndexJson as ConceptIndexEntry[];
