// GENERATED BY content/build-temple-facades.mjs — NÃO EDITAR MANUALMENTE.
// Manifest de conceitos (split): leve, pode entrar no bundle base. O índice e
// os corpos por domínio continuam em chunks próprios carregados sob demanda.
import type { TempleConcept } from '../../types';

export interface ConceptDomainInfo {
  id: string;
  name: string;
}

const CONCEPT_DOMAINS: ConceptDomainInfo[] = [{"id":"domain-01-fundamentos-psicologicos","name":"Fundamentos Psicologicos"},{"id":"domain-02-cognicao-e-processos-mentais","name":"Cognicao E Processos Mentais"},{"id":"domain-03-emocao-afeto-e-motivacao","name":"Emocao Afeto E Motivacao"},{"id":"domain-04-personalidade-self-e-identidade","name":"Personalidade Self E Identidade"},{"id":"domain-05-desenvolvimento-humano","name":"Desenvolvimento Humano"},{"id":"domain-06-aprendizagem-e-comportamento","name":"Aprendizagem E Comportamento"},{"id":"domain-07-relacoes-e-processos-interpessoais","name":"Relacoes E Processos Interpessoais"},{"id":"domain-08-processos-sociais-culturais-e-contextuais","name":"Processos Sociais Culturais E Contextuais"},{"id":"domain-09-psicopatologia-e-sofrimento-psicologico","name":"Psicopatologia E Sofrimento Psicologico"},{"id":"domain-10-processos-psicodinamicos-e-inconscientes","name":"Processos Psicodinamicos E Inconscientes"},{"id":"domain-11-processos-de-psicoterapia-e-mudanca","name":"Processos De Psicoterapia E Mudanca"},{"id":"domain-12-existencia-significado-e-construcao-da-experiencia","name":"Existencia Significado E Construcao Da Experiencia"}];

const CONCEPT_CHUNKS: Record<string, () => Promise<{ default: TempleConcept[] }>> = {
  'domain-01-fundamentos-psicologicos': async (): Promise<{ default: TempleConcept[] }> => {
    const chunk = await import('./concepts/domain-01-fundamentos-psicologicos.json');
    return { default: chunk.default as unknown as TempleConcept[] };
  },

  'domain-02-cognicao-e-processos-mentais': async (): Promise<{ default: TempleConcept[] }> => {
    const chunk = await import('./concepts/domain-02-cognicao-e-processos-mentais.json');
    return { default: chunk.default as unknown as TempleConcept[] };
  },

  'domain-03-emocao-afeto-e-motivacao': async (): Promise<{ default: TempleConcept[] }> => {
    const chunk = await import('./concepts/domain-03-emocao-afeto-e-motivacao.json');
    return { default: chunk.default as unknown as TempleConcept[] };
  },

  'domain-04-personalidade-self-e-identidade': async (): Promise<{ default: TempleConcept[] }> => {
    const chunk = await import('./concepts/domain-04-personalidade-self-e-identidade.json');
    return { default: chunk.default as unknown as TempleConcept[] };
  },

  'domain-05-desenvolvimento-humano': async (): Promise<{ default: TempleConcept[] }> => {
    const chunk = await import('./concepts/domain-05-desenvolvimento-humano.json');
    return { default: chunk.default as unknown as TempleConcept[] };
  },

  'domain-06-aprendizagem-e-comportamento': async (): Promise<{ default: TempleConcept[] }> => {
    const chunk = await import('./concepts/domain-06-aprendizagem-e-comportamento.json');
    return { default: chunk.default as unknown as TempleConcept[] };
  },

  'domain-07-relacoes-e-processos-interpessoais': async (): Promise<{ default: TempleConcept[] }> => {
    const chunk = await import('./concepts/domain-07-relacoes-e-processos-interpessoais.json');
    return { default: chunk.default as unknown as TempleConcept[] };
  },

  'domain-08-processos-sociais-culturais-e-contextuais': async (): Promise<{ default: TempleConcept[] }> => {
    const chunk = await import('./concepts/domain-08-processos-sociais-culturais-e-contextuais.json');
    return { default: chunk.default as unknown as TempleConcept[] };
  },

  'domain-09-psicopatologia-e-sofrimento-psicologico': async (): Promise<{ default: TempleConcept[] }> => {
    const chunk = await import('./concepts/domain-09-psicopatologia-e-sofrimento-psicologico.json');
    return { default: chunk.default as unknown as TempleConcept[] };
  },

  'domain-10-processos-psicodinamicos-e-inconscientes': async (): Promise<{ default: TempleConcept[] }> => {
    const chunk = await import('./concepts/domain-10-processos-psicodinamicos-e-inconscientes.json');
    return { default: chunk.default as unknown as TempleConcept[] };
  },

  'domain-11-processos-de-psicoterapia-e-mudanca': async (): Promise<{ default: TempleConcept[] }> => {
    const chunk = await import('./concepts/domain-11-processos-de-psicoterapia-e-mudanca.json');
    return { default: chunk.default as unknown as TempleConcept[] };
  },

  'domain-12-existencia-significado-e-construcao-da-experiencia': async (): Promise<{ default: TempleConcept[] }> => {
    const chunk = await import('./concepts/domain-12-existencia-significado-e-construcao-da-experiencia.json');
    return { default: chunk.default as unknown as TempleConcept[] };
  },
};

export const conceptDomains = CONCEPT_DOMAINS;

export function conceptChunkLoader(domainId: string) {
  return CONCEPT_CHUNKS[domainId] ?? null;
}
