// GENERATED BY content/build-temple-facades.mjs — NÃO EDITAR MANUALMENTE.
import registryJson from './approachRegistry.json' with { type: 'json' };

export interface ApproachRegistryFile {
  schemaVersion: number;
  generatedAt: string;
  stats: Record<string, number>;
  entries: Array<{
    id: string;
    name: string;
    system: string;
    familyId: string | null;
    aliases: Array<{ id: string; source: string; packageName?: string }>;
    taxonomyFamilyId?: string | null;
  }>;
  resolve: Record<string, string>;
}

export const approachRegistryFile = registryJson as unknown as ApproachRegistryFile;

/** Resolve qualquer id de abordagem (editorial/taxonomic/técnicas) → canônica. */
export function resolveApproach(aliasId: string):
  | { id: string; name: string; familyId: string | null }
  | null {
  const canonicalId = approachRegistryFile.resolve[aliasId];
  if (!canonicalId) return null;
  const entry = approachRegistryFile.entries.find((e) => e.id === canonicalId);
  if (!entry) return null;
  return { id: entry.id, name: entry.name, familyId: entry.familyId };
}
