// GENERATED BY content/build-temple-facades.mjs — NÃO EDITAR MANUALMENTE.
import type { TempleTechnique, TempleTechniqueCategory } from '../../types';
import techniquesJson from './techniques.json' with { type: 'json' };

interface TechniquesFile {
  categories: TempleTechniqueCategory[];
  techniques: TempleTechnique[];
}

export const techniqueCategories = (techniquesJson as unknown as TechniquesFile).categories;
export const templeTechniques = (techniquesJson as unknown as TechniquesFile).techniques;
