// GENERATED BY scripts/build-psicoterapia.mjs — NÃO EDITAR MANUALMENTE.
// Fonte: library/cecistudy_base_psicoterapias/entregas/*.md (97 abordagens, 10 famílias).
import type { PsicoterapiaFamily } from '../types';

export const PSICOTERAPIA_FAMILIES: PsicoterapiaFamily[] = [
  {
    "id": "fam-01",
    "order": 1,
    "name": "Psicanalítica e Psicodinâmica",
    "description": "Família de tradições clínicas derivadas, direta ou indiretamente, da psicanálise, que investigam processos inconscientes, conflitos e defesas, desenvolvimento da personalidade, relações internalizadas e padrões interpessoais, utilizando a relação terapêutica como importante campo de observação e mudança.",
    "color": "#BFDDED",
    "approachCount": 10
  },
  {
    "id": "fam-02",
    "order": 2,
    "name": "Existencial-Humanista",
    "description": "Família de abordagens que privilegia experiência vivida, autonomia, relação, autenticidade, sentido, liberdade responsável e potencial de crescimento. Inclui escolas distintas, unidas mais por ênfases filosóficas e clínicas do que por um protocolo único.",
    "color": "#DCCBB8",
    "approachCount": 10
  },
  {
    "id": "fam-03",
    "order": 3,
    "name": "Comportamental",
    "description": "Família de teorias e intervenções clínicas orientadas por princípios de aprendizagem, análise funcional, contingências e modificação de padrões observáveis de ação, evitando tratar comportamento como simples traço isolado ou sinônimo de obediência.",
    "color": "#C9E0D2",
    "approachCount": 10
  },
  {
    "id": "fam-04",
    "order": 4,
    "name": "Cognitiva e Cognitivo-Comportamental",
    "description": "Família de intervenções que formula sofrimento psicológico pela interação entre avaliações, crenças, atenção, comportamento, emoção e contexto, combinando colaboração clínica, formulação de caso, experimentos e estratégias cognitivas, comportamentais e experienciais.",
    "color": "#E8AFC0",
    "approachCount": 10
  },
  {
    "id": "fam-05",
    "order": 5,
    "name": "Sistêmica, Familiar e de Casais",
    "description": "Família de abordagens que compreende problemas e possibilidades de mudança em redes de relação, padrões de comunicação, ciclos de vida, fronteiras, significados e contextos sociais, trabalhando com indivíduos, casais, famílias e sistemas mais amplos.",
    "color": "#F0D9B4",
    "approachCount": 10
  },
  {
    "id": "fam-06",
    "order": 6,
    "name": "Construtivista e Narrativa",
    "description": "Família de abordagens que enfatiza construção de significados, narrativas, linguagem, identidade, relações dialógicas e colaboração na transformação de problemas e possibilidades de ação.",
    "color": "#C9D3E8",
    "approachCount": 11
  },
  {
    "id": "fam-07",
    "order": 7,
    "name": "Interpessoal e Relacional Contemporânea",
    "description": "Família de abordagens que compreende sofrimento e mudança a partir de padrões de vínculo, relações significativas, apego, capacidades de mentalização, comunicação e experiências interpessoais atuais e históricas.",
    "color": "#E2C9E0",
    "approachCount": 9
  },
  {
    "id": "fam-08",
    "order": 8,
    "name": "Integrativa e Eclética",
    "description": "Família de propostas que combinam de modo teoricamente justificado diferentes modelos, técnicas ou princípios de mudança, distinguindo integração clínica responsável de mera justaposição de procedimentos.",
    "color": "#D6D0E8",
    "approachCount": 9
  },
  {
    "id": "fam-09",
    "order": 9,
    "name": "Social, Cultural e de Gênero",
    "description": "Família de perspectivas clínicas transversais que situam sofrimento, cuidado e relação terapêutica em contextos de poder, cultura, raça/etnia, gênero, sexualidade, classe, deficiência, migração e outras formas de diferença socialmente produzida.",
    "color": "#E8C9CD",
    "approachCount": 9
  },
  {
    "id": "fam-10",
    "order": 10,
    "name": "Modelos Pragmáticos e Focados em Objetivo",
    "description": "Família de intervenções breves ou estruturadas que organizam o trabalho clínico em torno de metas, recursos, escolhas, resolução de problemas, motivação e mudanças observáveis, sem pressupor que profundidade clínica dependa necessariamente de longa duração.",
    "color": "#CDE4E8",
    "approachCount": 9
  }
];
