// GENERATED BY script — split into src/data/psicoterapia/.
// NÃO EDITAR MANUALMENTE. Use src/data/psicoterapia/index.ts.
export { PSICOTERAPIA_APPROACHES } from './psicoterapia';
export type { PsychologyApproach } from './psicoterapia';
